
#
# Module Manifest for Module 'NVR_GitScripts
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Author   : NAVERTICA\ksacek
#
# Generated: 2015-12-07
#

@{

# Module Loader File
ModuleToProcess = 'loader.psm1'

# Version Number
ModuleVersion = '1.0'

# Unique Module ID
GUID = 'ad472484-a520-4166-8bda-63bd59ec56a5'

# Module Author
Author = 'NAVERTICA\ksacek'

# Company
CompanyName = 'Created by ISESteroids'

# Copyright
Copyright = '(c) 2015 NAVERTICA\ksacek. All rights reserved.'

# Module Description
Description = ''

# Minimum PowerShell Version Required
PowerShellVersion = ''

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = ''

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
FormatsToProcess = @()

# 
NestedModules = @()

# List of exportable functions
FunctionsToExport = '*'

# List of exportable cmdlets
CmdletsToExport = '*'

# List of exportable variables
VariablesToExport = '*'

# List of exportable aliases
AliasesToExport = '*'

# List of all modules contained in this module
ModuleList = @()

# List of all files contained in this module
FileList = @()

# Private data that needs to be passed to this module
PrivateData = ''

}